name = "hono-backend"
main = "src/index.ts"
compatibility_date = "2025-08-17"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "STAGE"
# URL of your Cloudflare Pages site
FRONTEND_URL = " https://www.pengfloor.com/"
# OAuth redirect URI configured in Google Console
GOOGLE_REDIRECT_URI = "https://www.pengfloor.com/api/auth/google/callback"