name = "hono-backend"
main = "src/index.ts"
compatibility_date = "2025-08-17"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "STAGE"
# URL of your Cloudflare Pages site
FRONTEND_URL = "https://pngfloor.pages.dev/"
# OAuth redirect URI configured in Google Console
GOOGLE_REDIRECT_URI = "https://hono-backend.jasonpeng.workers.dev/api/auth/google/callback"